name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/kmitl-fullstack-b/fullstack-b-2567-backend:${{ github.sha }}
            ${{ secrets.DOCKER_REGISTRY }}/kmitl-fullstack-b/fullstack-b-2567-backend:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/kmitl-fullstack-b/fullstack-b-2567-backend:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/kmitl-fullstack-b/fullstack-b-2567-backend:buildcache,mode=max

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -e

            echo "=== Deployment Started ==="
            cd ~/app

            echo "Docker login..."
            docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

            echo "Pulling latest image..."
            docker pull ${{ secrets.DOCKER_REGISTRY }}/kmitl-fullstack-b/fullstack-b-2567-backend:${{ github.sha }}

            echo "Generating docker-compose.yml..."
            cat > docker-compose.yml << COMPOSE
          version: "3"
          services:
            app:
              image: ${{ secrets.DOCKER_REGISTRY }}/kmitl-fullstack-b/fullstack-b-2567-backend:${{ github.sha }}
              restart: always
              ports:
                - "3000:3000"
              env_file:
                - .env-backend
              healthcheck:
                test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
                interval: 30s
                timeout: 10s
                retries: 3
                start_period: 10s
          COMPOSE

                      echo "Deploying app..."
                      docker-compose down
                      docker-compose up -d

                      echo "Cleaning up old Docker images..."
                      docker image prune -af --filter "until=24h"
                      docker images "${{ secrets.DOCKER_REGISTRY }}/kmitl-fullstack-b/fullstack-b-2567-backend" --format "{{.ID}}" | tail -n +4 | xargs -r docker rmi

                      echo "✅ Deployment complete!"
          EOF